### PR TITLE
Changes to config documenation

### PR DESCRIPTION
**Pull request by mindspank**
Swapping out : for = so lazy copy pasters like myself don't have to change it :)

### CODE REVIEW

**Comment by mindspank** [comment]
I tried running gulp verb to update the readme.md but it throw an error. Weren't sure I could run the full build cycle as that publishes to npm
`Error: Cannot find module './lib/'`

**Comment by stefanwalther** [comment]
Hi, the full build-cycle included sense-go which currently needs to be linked, not fully working in the released branch. No problem, will take care of it. Thx, you are absolutely right.
(BTW: Will also remove sense-go here, so that it is easier for others to run the tests).

**Comment by theredpea** [comment]
Great tool, but I think this is important Pull Request :)

**Comment by stefanwalther** [comment]
Closed with fa83a125d7ebdb67f1a63886692cb065002ef3c7

**Pull request closed without merging**
